#!/usr/bin/env node
/**
 * Bundles `content/posts/*.md` into a TypeScript module.
 *
 * The markdown files are the source of truth for the seed posts, but a Vercel
 * serverless function has no reliable view of the repository's working tree.
 * Rather than fight file tracing, the files are compiled into a module that
 * the filesystem repository imports. Run via `npm run content:build`; it is
 * wired into `predev`, `prebuild` and CI so the checked-in output cannot drift.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const workspaceRoot = resolve(here, '../..');
const contentDir = join(workspaceRoot, 'content/posts');
const outputFile = join(workspaceRoot, 'apps/api/src/content/generated-content.ts');

const HEADER = `// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by tools/scripts/generate-content.mjs — do not edit by hand.
// Edit the markdown in content/posts/ and run \`npm run content:build\`.
// ─────────────────────────────────────────────────────────────────────────────

export interface RawPostFile {
  slug: string;
  filename: string;
  source: string;
}

`;

async function main() {
  let filenames = [];
  try {
    filenames = (await readdir(contentDir)).filter((name) => /\.mdx?$/i.test(name)).sort();
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
    console.warn(`[content] no ${contentDir} directory; emitting an empty bundle`);
  }

  const entries = [];
  for (const filename of filenames) {
    const source = await readFile(join(contentDir, filename), 'utf8');
    const slug = filename.replace(/\.mdx?$/i, '');
    entries.push({ slug, filename, source });
  }

  const body =
    `export const RAW_POSTS: RawPostFile[] = [\n` +
    entries
      .map(
        (entry) =>
          `  {\n    slug: ${JSON.stringify(entry.slug)},\n` +
          `    filename: ${JSON.stringify(entry.filename)},\n` +
          `    source: ${JSON.stringify(entry.source)},\n  },`
      )
      .join('\n') +
    `\n];\n`;

  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(outputFile, HEADER + body, 'utf8');

  const bytes = entries.reduce((total, entry) => total + entry.source.length, 0);
  console.log(`[content] bundled ${entries.length} post(s), ${bytes} bytes → ${outputFile}`);
}

main().catch((error) => {
  console.error('[content] generation failed');
  console.error(error);
  process.exitCode = 1;
});
